apiVersion: v1
kind: ConfigMap
metadata:
  name: mynginx
data:
  index.html: "<html><h1>This is nginx web service v1.13</h1><html>"
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx_svc
spec:
  type: NodePort
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: mynginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      volumes:
        - name: volmap
          configMap:
            name: mynginx
      containers:
        - name: mynginx
          image: nginx:1.13
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volmap
              mountPath: /usr/share/nginx/html/
